Auto-inserting items to inventory
Electrical-Age/ElectricalAge pull request #584
Opened 2016-12-30 22:23 UTC by cm0x4D

Sometimes it makes actually sense to auto-install items into nodes (#579) just by right-clicking with the correct item.

This PR tries to generalize the concept and adds this feature to a maximum of possible EA elements.

Ready to merge when

- [ ] Replace LampSocket implementation by generic process
- [ ] Make the process more flexible (more conditions when to actually insert/replace) 
- Add for more items (ideas welcome)
  - [ ] Installing drills into the auto miner
  - [ ] Refilling pipes in the auto miner
  - [ ] Installing Ferromagnetic Cores
  - [ ] Placing regulators in machines
  - [ ] Upgrading panels with the Solar Tracker
  - ...

2017-01-06 09:04 UTC, AMIDIBOSS requested changes
Items already in inventory slot may get back into player's inventory

2017-01-06 23:05 UTC, cm0x4D commented
> Items already in inventory slot may get back into player's inventory

It is not that simple - what if the itemstack had more than one item? What if the inventory does not have any free slots left? The MC API is not that straightforward either. 

I decided to just drop the existing item and the player can take the item if he wants.

2017-01-11 15:40 UTC, Baughn commented on src/main/java/mods/eln/transparentnode/autominer/AutoMinerElement.java
> +	AutoAcceptInventoryProxy accpetingInventory =
This is misspelled. (IDEA conveniently does spell-checking if you ask it do.)

2017-01-11 19:15 UTC, cm0x4D commented
ready to merge

2017-01-13 01:37 UTC, Baughn commented
Tested on Erisia, and works fine (so far).

2017-01-14 13:35 UTC, cm0x4D commented
Ok, everything that makes sense for me is done. This might be already too much, I fear that we might confuse players with some of those...

2017-01-23 22:13 UTC, merged