added pneumaticraft gasoline, assuming it's petrol and not gasohol.
Electrical-Age/ElectricalAge pull request #610
Opened 2017-01-20 03:31 UTC by Castone22

2017-01-20 07:56 UTC, cm0x4D requested changes

2017-01-20 07:56 UTC, cm0x4D commented on src/main/java/mods/eln/fluid/FuelRegistry.kt
> +            "gasoline" to 25820000.0,   // PneumaticCraft, density = 0.755 kg/L, heat value = 34,2 MJ/l
How could be gasoline not on the gasoline list? ^^

Should fuel and gasoline not have about the same heating value?

2017-01-20 13:40 UTC, Baughn commented on src/main/java/mods/eln/fluid/FuelRegistry.kt
> +            "gasoline" to 25820000.0,   // PneumaticCraft, density = 0.755 kg/L, heat value = 34,2 MJ/l
As a matter of game-balance, probably not. Buildcraft fuel is the most expensive type on the list, more or less -- in terms of time spent getting it, not machinery. It makes sense for it to have higher density, as that also translates to higher maximum power output.

As a matter of realism... it's easy to see where the gasoline numbers come from, and they make sense. I'm not sure what material 'fuel' is supposed to be.

2017-01-20 20:22 UTC, cm0x4D commented on src/main/java/mods/eln/fluid/FuelRegistry.kt
> +            "gasoline" to 25820000.0,   // PneumaticCraft, density = 0.755 kg/L, heat value = 34,2 MJ/l
Ok then, so fuel is better and close to kerosine. Works.

2017-01-20 20:23 UTC, cm0x4D approved these changes

2017-01-20 20:24 UTC, cm0x4D approved these changes

2017-01-21 07:59 UTC, merged

2017-01-21 07:59 UTC, cm0x4D commented
Merged, thank you @Castone22!