Let users the choice between symbols and renderings of the blocks
Electrical-Age/ElectricalAge pull request #712
Opened 2017-03-24 23:04 UTC by cm0x4D

Not ready to merge, a lot of icons have to be added...

2017-03-25 17:05 UTC, AMIDIBOSS commented
Nice feature!
˙˙˙sƃuıɹǝpuǝɹ ǝɥʇ ǝsooɥɔ p,ı

2017-03-27 19:56 UTC, cm0x4D commented
@Baughn This PR does not only add the config to choose between symbols and renderings, it does replace every rendered item with an icon, so this might actually help in porting to 1.10+...

2017-03-28 12:21 UTC, Baughn requested changes

2017-03-28 12:21 UTC, Baughn commented on src/main/java/mods/eln/generic/GenericItemBlockUsingDamageDescriptor.java
> +        changeDefaultIcon(iconName);
Might be better named "setDefaultIcon".

2017-03-28 12:21 UTC, Baughn commented on src/main/java/mods/eln/gridnode/GridDescriptor.java
> -        objItemScale(obj);
I converted this whole thing to Kotlin in a separate PR I haven't finished yet...

Oh, I won't stop you. But this will be fun.

2017-03-28 12:21 UTC, Baughn commented on src/main/java/mods/eln/sixnode/Scanner.kt
> +        voltageLevelColor = VoltageLevelColor.SignalVoltage
These shouldn't normally change, so an abstract / open val in the superclass might do better.

2017-03-28 12:21 UTC, Baughn commented on src/main/java/mods/eln/sixnode/TreeResinCollector/TreeResinCollectorDescriptor.java
>      public boolean use2DIcon() {
Are there any use2DIcon implementations left that return false?

2017-03-28 16:54 UTC, AMIDIBOSS commented on src/main/java/mods/eln/misc/VoltageLevelColor.java
> +    Grid("grid"),
There will be a few grid voltages, 2 for now. What colors will they have?

2017-03-29 21:08 UTC, cm0x4D commented on src/main/java/mods/eln/sixnode/TreeResinCollector/TreeResinCollectorDescriptor.java
>      public boolean use2DIcon() {
I can remove it already for GenericItemBlockUsingDamageDescriptor subclasses.

Some items (GenericItemUsingDamageDescriptor subclasses) do still return false in order to do some custom rendering. Have to address them later.

2017-03-29 21:23 UTC, cm0x4D commented on src/main/java/mods/eln/sixnode/Scanner.kt
> +        voltageLevelColor = VoltageLevelColor.SignalVoltage
It is just a field in the base class, I would have to add a getter and setter to convert it to a property?

2017-03-29 21:23 UTC, cm0x4D commented on src/main/java/mods/eln/misc/VoltageLevelColor.java
> +    Grid("grid"),
Same as high and very high, but with a pattern.

2017-03-29 22:15 UTC, Baughn commented on src/main/java/mods/eln/sixnode/Scanner.kt
> +        voltageLevelColor = VoltageLevelColor.SignalVoltage
No, you can override fields in Kotlin. ..though then it'd need to be Kotlin. Perhaps not.

2017-03-29 22:16 UTC, Baughn approved these changes

2017-03-30 04:25 UTC, merged